version: "3.9"
services:
  app:
    image: renatakb/ecomm:1.1
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongo-ecomm
    depends_on:
      - mongo-ecomm

  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: ./mongo
        target: /mongo-scripts
    ports:
      - "27017:27017"
    expose:
      - "27017"

volumes:
  db-mongo-ecomm:
